version: '3.0'

volumes:
  db-data:
    driver: local
  redis-data:
    driver: local

services:
  db:
    image: postgres:15.1-alpine
    env_file:
      - .env
    ports:
      - '5437:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

